/**
 * Chữ của trang Cộng đồng (CommunityHub) cho cả 10 ngôn ngữ.
 * Mỗi khóa là một mảng theo ĐÚNG thứ tự: vi, en, ja, zh, ko, fr, de, es, ru, pt.
 * Chuỗi có {n}, {q}, {name}, {names} được thay bằng hàm fmt() trong CommunityHub.
 */
const ORDER = ['vi', 'en', 'ja', 'zh', 'ko', 'fr', 'de', 'es', 'ru', 'pt'];

const E = {
  brand: ['GitXplore', 'GitXplore', 'GitXplore', 'GitXplore', 'GitXplore', 'GitXplore', 'GitXplore', 'GitXplore', 'GitXplore', 'GitXplore'],
  title: ['Cộng đồng', 'Community', 'コミュニティ', '社区', '커뮤니티', 'Communauté', 'Community', 'Comunidad', 'Сообщество', 'Comunidade'],
  search_ph: ['Tìm kiếm thành viên', 'Search members', 'メンバーを検索', '搜索成员', '멤버 검색', 'Rechercher des membres', 'Mitglieder suchen', 'Buscar miembros', 'Поиск участников', 'Buscar membros'],
  group_forum: ['Diễn đàn', 'Forum', 'フォーラム', '论坛', '포럼', 'Forum', 'Forum', 'Foro', 'Форум', 'Fórum'],
  group_settings: ['Cài đặt', 'Settings', '設定', '设置', '설정', 'Paramètres', 'Einstellungen', 'Ajustes', 'Настройки', 'Configurações'],
  nav_home: ['Trang chủ', 'Home', 'ホーム', '主页', '홈', 'Accueil', 'Startseite', 'Inicio', 'Главная', 'Início'],
  nav_requests: ['Lời mời kết bạn', 'Friend requests', 'フレンドリクエスト', '好友请求', '친구 요청', 'Demandes d’ami', 'Freundschaftsanfragen', 'Solicitudes de amistad', 'Заявки в друзья', 'Pedidos de amizade'],
  nav_suggestions: ['Gợi ý', 'Suggestions', 'おすすめ', '推荐', '추천', 'Suggestions', 'Vorschläge', 'Sugerencias', 'Рекомендации', 'Sugestões'],
  nav_friends: ['Tất cả bạn bè', 'All friends', 'すべての友達', '所有好友', '모든 친구', 'Tous les amis', 'Alle Freunde', 'Todos los amigos', 'Все друзья', 'Todos os amigos'],
  nav_birthdays: ['Sinh nhật', 'Birthdays', '誕生日', '生日', '생일', 'Anniversaires', 'Geburtstage', 'Cumpleaños', 'Дни рождения', 'Aniversários'],
  nav_lists: ['Danh sách tùy chỉnh', 'Custom lists', 'カスタムリスト', '自定义列表', '맞춤 목록', 'Listes personnalisées', 'Eigene Listen', 'Listas personalizadas', 'Свои списки', 'Listas personalizadas'],
  nav_topics: ['Chủ đề mới', 'New topics', '新着トピック', '最新主题', '새 주제', 'Nouveaux sujets', 'Neue Themen', 'Temas nuevos', 'Новые темы', 'Novos tópicos'],
  nav_settings: ['Hồ sơ & ngôn ngữ', 'Profile & language', 'プロフィールと言語', '个人资料与语言', '프로필 & 언어', 'Profil et langue', 'Profil & Sprache', 'Perfil e idioma', 'Профиль и язык', 'Perfil e idioma'],
  req_title: ['Lời mời kết bạn', 'Friend requests', 'フレンドリクエスト', '好友请求', '친구 요청', 'Demandes d’ami', 'Freundschaftsanfragen', 'Solicitudes de amistad', 'Заявки в друзья', 'Pedidos de amizade'],
  sug_title: ['Những người bạn có thể biết', 'People you may know', '知り合いかも', '你可能认识的人', '알 수도 있는 사람', 'Personnes que vous connaissez peut-être', 'Personen, die du kennen könntest', 'Personas que quizá conozcas', 'Возможно, вы знакомы', 'Pessoas que você talvez conheça'],
  topics_title: ['Chủ đề mới', 'New topics', '新着トピック', '最新主题', '새 주제', 'Nouveaux sujets', 'Neue Themen', 'Temas nuevos', 'Новые темы', 'Novos tópicos'],
  see_all: ['Xem tất cả', 'See all', 'すべて見る', '查看全部', '모두 보기', 'Tout voir', 'Alle ansehen', 'Ver todo', 'Смотреть все', 'Ver tudo'],
  confirm: ['Xác nhận', 'Confirm', '承認', '确认', '확인', 'Confirmer', 'Bestätigen', 'Confirmar', 'Подтвердить', 'Confirmar'],
  delete: ['Xóa', 'Delete', '削除', '删除', '삭제', 'Supprimer', 'Löschen', 'Eliminar', 'Удалить', 'Excluir'],
  add: ['Thêm bạn bè', 'Add friend', '友達を追加', '加好友', '친구 추가', 'Ajouter', 'Hinzufügen', 'Agregar amigo', 'Добавить в друзья', 'Adicionar amigo'],
  cancel_req: ['Hủy lời mời', 'Cancel request', 'リクエストを取り消す', '取消请求', '요청 취소', 'Annuler la demande', 'Anfrage zurückziehen', 'Cancelar solicitud', 'Отменить заявку', 'Cancelar pedido'],
  hide: ['Gỡ', 'Remove', '非表示', '移除', '숨기기', 'Retirer', 'Entfernen', 'Quitar', 'Убрать', 'Remover'],
  unfriend: ['Hủy kết bạn', 'Unfriend', '友達を解除', '解除好友', '친구 끊기', 'Retirer des amis', 'Freundschaft beenden', 'Eliminar amistad', 'Удалить из друзей', 'Desfazer amizade'],
  is_friend: ['✓ Bạn bè', '✓ Friends', '✓ 友達', '✓ 好友', '✓ 친구', '✓ Amis', '✓ Freunde', '✓ Amigos', '✓ Друзья', '✓ Amigos'],
  in_list: ['Danh sách', 'Lists', 'リスト', '列表', '목록', 'Listes', 'Listen', 'Listas', 'Списки', 'Listas'],
  view_topic: ['Xem chủ đề', 'View topic', 'トピックを見る', '查看主题', '주제 보기', 'Voir le sujet', 'Thema ansehen', 'Ver tema', 'Открыть тему', 'Ver tópico'],
  hide_topic: ['Ẩn', 'Hide', '非表示', '隐藏', '숨기기', 'Masquer', 'Ausblenden', 'Ocultar', 'Скрыть', 'Ocultar'],
  mutual: ['{n} bạn chung', '{n} mutual friends', '共通の友達 {n} 人', '{n} 位共同好友', '함께 아는 친구 {n}명', '{n} amis en commun', '{n} gemeinsame Freunde', '{n} amigos en común', 'Общих друзей: {n}', '{n} amigos em comum'],
  no_mutual: ['Thành viên GitXplore', 'GitXplore member', 'GitXplore メンバー', 'GitXplore 成员', 'GitXplore 멤버', 'Membre GitXplore', 'GitXplore-Mitglied', 'Miembro de GitXplore', 'Участник GitXplore', 'Membro do GitXplore'],
  replies: ['phản hồi', 'replies', '件の返信', '条回复', '개의 답글', 'réponses', 'Antworten', 'respuestas', 'ответов', 'respostas'],
  tab_received: ['Đã nhận', 'Received', '受信', '已收到', '받은 요청', 'Reçues', 'Erhalten', 'Recibidas', 'Полученные', 'Recebidos'],
  tab_sent: ['Đã gửi', 'Sent', '送信', '已发送', '보낸 요청', 'Envoyées', 'Gesendet', 'Enviadas', 'Отправленные', 'Enviados'],
  empty_req: ['Bạn không có lời mời nào.', 'You have no requests.', 'リクエストはありません。', '你没有任何请求。', '받은 요청이 없습니다.', 'Vous n’avez aucune demande.', 'Du hast keine Anfragen.', 'No tienes solicitudes.', 'У вас нет заявок.', 'Você não tem pedidos.'],
  empty_sent: ['Bạn chưa gửi lời mời nào.', 'You haven’t sent any requests.', '送信したリクエストはありません。', '你还没有发送过请求。', '보낸 요청이 없습니다.', 'Vous n’avez envoyé aucune demande.', 'Du hast noch keine Anfragen gesendet.', 'No has enviado ninguna solicitud.', 'Вы ещё не отправляли заявок.', 'Você ainda não enviou pedidos.'],
  empty_sug: ['Chưa có gợi ý nào. Khi có thêm thành viên vào cộng đồng, họ sẽ xuất hiện ở đây.', 'No suggestions yet. They will show up as more members join the community.', 'まだおすすめはありません。メンバーが増えるとここに表示されます。', '暂时没有推荐。有更多成员加入社区后会显示在这里。', '아직 추천이 없습니다. 멤버가 늘어나면 여기에 표시됩니다.', 'Aucune suggestion pour le moment. Elles apparaîtront quand d’autres membres rejoindront la communauté.', 'Noch keine Vorschläge. Sie erscheinen hier, sobald mehr Mitglieder beitreten.', 'Aún no hay sugerencias. Aparecerán cuando se unan más miembros a la comunidad.', 'Пока нет рекомендаций. Они появятся, когда в сообщество придёт больше участников.', 'Ainda não há sugestões. Elas aparecerão quando mais membros entrarem na comunidade.'],
  empty_friends: ['Bạn chưa có bạn bè nào. Hãy xem mục Gợi ý.', 'You have no friends yet. Check out Suggestions.', 'まだ友達がいません。「おすすめ」を見てみましょう。', '你还没有好友。去看看“推荐”吧。', '아직 친구가 없습니다. 추천을 확인해 보세요.', 'Vous n’avez pas encore d’amis. Consultez les suggestions.', 'Du hast noch keine Freunde. Schau dir die Vorschläge an.', 'Aún no tienes amigos. Mira las sugerencias.', 'У вас пока нет друзей. Загляните в рекомендации.', 'Você ainda não tem amigos. Veja as sugestões.'],
  empty_search: ['Không tìm thấy ai.', 'No one found.', '該当するメンバーはいません。', '没有找到任何人。', '검색 결과가 없습니다.', 'Personne trouvé.', 'Niemand gefunden.', 'No se encontró a nadie.', 'Никого не найдено.', 'Ninguém encontrado.'],
  empty_topics: ['Chưa có chủ đề nào.', 'No topics yet.', 'まだトピックはありません。', '暂无主题。', '아직 주제가 없습니다.', 'Aucun sujet pour le moment.', 'Noch keine Themen.', 'Aún no hay temas.', 'Тем пока нет.', 'Ainda não há tópicos.'],
  friends_count: ['{n} người bạn', '{n} friends', '友達 {n} 人', '{n} 位好友', '친구 {n}명', '{n} amis', '{n} Freunde', '{n} amigos', 'Друзей: {n}', '{n} amigos'],
  filter_ph: ['Tìm trong danh sách bạn bè', 'Search your friends', '友達を検索', '搜索你的好友', '친구 검색', 'Rechercher parmi vos amis', 'Freunde durchsuchen', 'Buscar entre tus amigos', 'Поиск среди друзей', 'Buscar entre seus amigos'],
  search_title: ['Kết quả cho “{q}”', 'Results for “{q}”', '「{q}」の検索結果', '“{q}”的搜索结果', '“{q}” 검색 결과', 'Résultats pour « {q} »', 'Ergebnisse für „{q}“', 'Resultados para “{q}”', 'Результаты по запросу «{q}»', 'Resultados para “{q}”'],
  bd_banner: ['🎂 Hôm nay là sinh nhật của {names}', '🎂 Today is the birthday of {names}', '🎂 今日は {names} さんの誕生日です', '🎂 今天是 {names} 的生日', '🎂 오늘은 {names}님의 생일입니다', '🎂 Aujourd’hui, c’est l’anniversaire de {names}', '🎂 Heute hat {names} Geburtstag', '🎂 Hoy es el cumpleaños de {names}', '🎂 Сегодня день рождения у {names}', '🎂 Hoje é aniversário de {names}'],
  bd_today: ['Sinh nhật hôm nay', 'Today’s birthdays', '今日の誕生日', '今天的生日', '오늘의 생일', 'Anniversaires du jour', 'Heutige Geburtstage', 'Cumpleaños de hoy', 'Сегодняшние дни рождения', 'Aniversários de hoje'],
  bd_upcoming: ['Sắp tới (30 ngày)', 'Upcoming (30 days)', '今後30日間', '即将到来（30 天内）', '다가오는 생일 (30일)', 'À venir (30 jours)', 'Demnächst (30 Tage)', 'Próximos (30 días)', 'Ближайшие (30 дней)', 'Próximos (30 dias)'],
  bd_none: ['Không có sinh nhật nào trong 30 ngày tới.', 'No birthdays in the next 30 days.', '今後30日間に誕生日はありません。', '未来 30 天内没有生日。', '앞으로 30일 동안 생일이 없습니다.', 'Aucun anniversaire dans les 30 prochains jours.', 'Keine Geburtstage in den nächsten 30 Tagen.', 'No hay cumpleaños en los próximos 30 días.', 'В ближайшие 30 дней дней рождения нет.', 'Nenhum aniversário nos próximos 30 dias.'],
  bd_missing: ['Chưa cập nhật ngày sinh', 'Birthday not set', '誕生日未設定', '未设置生日', '생일 미설정', 'Anniversaire non renseigné', 'Geburtstag nicht angegeben', 'Cumpleaños sin definir', 'Дата рождения не указана', 'Aniversário não definido'],
  bd_tomorrow: ['Ngày mai', 'Tomorrow', '明日', '明天', '내일', 'Demain', 'Morgen', 'Mañana', 'Завтра', 'Amanhã'],
  bd_in_days: ['Còn {n} ngày', 'In {n} days', 'あと {n} 日', '还有 {n} 天', '{n}일 남음', 'Dans {n} jours', 'In {n} Tagen', 'En {n} días', 'Через {n} дн.', 'Em {n} dias'],
  bd_turning: ['tròn {n} tuổi', 'turning {n}', '{n} 歳になります', '满 {n} 岁', '{n}세가 됩니다', 'fête ses {n} ans', 'wird {n}', 'cumple {n}', 'исполняется {n}', 'completa {n} anos'],
  lists_title: ['Danh sách tùy chỉnh', 'Custom lists', 'カスタムリスト', '自定义列表', '맞춤 목록', 'Listes personnalisées', 'Eigene Listen', 'Listas personalizadas', 'Свои списки', 'Listas personalizadas'],
  list_new_ph: ['Tên danh sách mới', 'New list name', '新しいリスト名', '新列表名称', '새 목록 이름', 'Nom de la nouvelle liste', 'Name der neuen Liste', 'Nombre de la nueva lista', 'Название нового списка', 'Nome da nova lista'],
  list_create: ['Tạo', 'Create', '作成', '创建', '만들기', 'Créer', 'Erstellen', 'Crear', 'Создать', 'Criar'],
  list_rename: ['Đổi tên', 'Rename', '名前を変更', '重命名', '이름 바꾸기', 'Renommer', 'Umbenennen', 'Renombrar', 'Переименовать', 'Renomear'],
  list_delete: ['Xóa danh sách', 'Delete list', 'リストを削除', '删除列表', '목록 삭제', 'Supprimer la liste', 'Liste löschen', 'Eliminar lista', 'Удалить список', 'Excluir lista'],
  list_none: ['Chưa có danh sách nào.', 'No lists yet.', 'まだリストはありません。', '还没有列表。', '아직 목록이 없습니다.', 'Aucune liste pour le moment.', 'Noch keine Listen.', 'Aún no hay listas.', 'Списков пока нет.', 'Ainda não há listas.'],
  list_empty: ['Danh sách này chưa có ai.', 'This list is empty.', 'このリストは空です。', '此列表还没有人。', '이 목록은 비어 있습니다.', 'Cette liste est vide.', 'Diese Liste ist leer.', 'Esta lista está vacía.', 'Этот список пуст.', 'Esta lista está vazia.'],
  list_add_pick: ['Chọn bạn bè để thêm…', 'Pick a friend to add…', '追加する友達を選択…', '选择要添加的好友…', '추가할 친구 선택…', 'Choisir un ami à ajouter…', 'Freund zum Hinzufügen wählen…', 'Elige un amigo para agregar…', 'Выберите друга для добавления…', 'Escolha um amigo para adicionar…'],
  list_add: ['Thêm', 'Add', '追加', '添加', '추가', 'Ajouter', 'Hinzufügen', 'Agregar', 'Добавить', 'Adicionar'],
  list_remove: ['Xóa khỏi danh sách', 'Remove from list', 'リストから削除', '从列表中移除', '목록에서 제거', 'Retirer de la liste', 'Aus Liste entfernen', 'Quitar de la lista', 'Убрать из списка', 'Remover da lista'],
  list_confirm: ['Xóa danh sách “{name}”?', 'Delete the list “{name}”?', 'リスト「{name}」を削除しますか？', '删除列表“{name}”？', '“{name}” 목록을 삭제할까요?', 'Supprimer la liste « {name} » ?', 'Liste „{name}“ löschen?', '¿Eliminar la lista “{name}”?', 'Удалить список «{name}»?', 'Excluir a lista “{name}”?'],
  list_prompt: ['Tên mới cho danh sách', 'New name for the list', 'リストの新しい名前', '列表的新名称', '목록의 새 이름', 'Nouveau nom de la liste', 'Neuer Name für die Liste', 'Nuevo nombre para la lista', 'Новое название списка', 'Novo nome da lista'],
  list_pick_one: ['Chọn một danh sách để xem.', 'Pick a list to view it.', '表示するリストを選んでください。', '选择一个列表来查看。', '볼 목록을 선택하세요.', 'Choisissez une liste pour l’afficher.', 'Wähle eine Liste zum Anzeigen.', 'Elige una lista para verla.', 'Выберите список для просмотра.', 'Escolha uma lista para visualizar.'],
  unfriend_confirm: ['Hủy kết bạn với {name}?', 'Unfriend {name}?', '{name} さんとの友達を解除しますか？', '解除与 {name} 的好友关系？', '{name}님과 친구를 끊을까요?', 'Retirer {name} de vos amis ?', 'Freundschaft mit {name} beenden?', '¿Eliminar a {name} de tus amigos?', 'Удалить {name} из друзей?', 'Desfazer amizade com {name}?'],
  settings_title: ['Hồ sơ & ngôn ngữ', 'Profile & language', 'プロフィールと言語', '个人资料与语言', '프로필 & 언어', 'Profil et langue', 'Profil & Sprache', 'Perfil e idioma', 'Профиль и язык', 'Perfil e idioma'],
  profile: ['Hồ sơ cộng đồng', 'Community profile', 'コミュニティプロフィール', '社区资料', '커뮤니티 프로필', 'Profil communautaire', 'Community-Profil', 'Perfil de la comunidad', 'Профиль в сообществе', 'Perfil da comunidade'],
  display_name: ['Tên hiển thị', 'Display name', '表示名', '显示名称', '표시 이름', 'Nom affiché', 'Anzeigename', 'Nombre visible', 'Отображаемое имя', 'Nome de exibição'],
  birthday: ['Ngày sinh', 'Birthday', '誕生日', '生日', '생일', 'Date de naissance', 'Geburtstag', 'Cumpleaños', 'Дата рождения', 'Aniversário'],
  bio: ['Giới thiệu', 'About', '自己紹介', '个人简介', '소개', 'À propos', 'Über mich', 'Acerca de ti', 'О себе', 'Sobre você'],
  bio_ph: ['Vài dòng về bạn…', 'A few lines about you…', 'あなたについて少し…', '写几句介绍自己…', '자신에 대해 간단히…', 'Quelques lignes sur vous…', 'Ein paar Zeilen über dich…', 'Unas líneas sobre ti…', 'Пара слов о себе…', 'Algumas linhas sobre você…'],
  save: ['Lưu thay đổi', 'Save changes', '変更を保存', '保存更改', '변경 사항 저장', 'Enregistrer', 'Änderungen speichern', 'Guardar cambios', 'Сохранить изменения', 'Salvar alterações'],
  lang_title: ['Ngôn ngữ', 'Language', '言語', '语言', '언어', 'Langue', 'Sprache', 'Idioma', 'Язык', 'Idioma'],
  lang_sub: ['Chọn ngôn ngữ hiển thị của GitXplore. Lựa chọn được lưu trên trình duyệt này.', 'Choose the display language for GitXplore. Saved on this browser.', 'GitXplore の表示言語を選択します。設定はこのブラウザに保存されます。', '选择 GitXplore 的显示语言。设置会保存在此浏览器中。', 'GitXplore 표시 언어를 선택하세요. 이 브라우저에 저장됩니다.', 'Choisissez la langue d’affichage de GitXplore. Enregistré dans ce navigateur.', 'Wähle die Anzeigesprache von GitXplore. Wird in diesem Browser gespeichert.', 'Elige el idioma de GitXplore. Se guarda en este navegador.', 'Выберите язык интерфейса GitXplore. Сохраняется в этом браузере.', 'Escolha o idioma do GitXplore. Fica salvo neste navegador.'],
  current: ['Đang dùng', 'Current', '使用中', '当前使用', '사용 중', 'Actuelle', 'Aktiv', 'Actual', 'Текущий', 'Atual'],
  login_need: ['Đăng nhập để dùng tính năng bạn bè của cộng đồng.', 'Sign in to use the community friends features.', 'コミュニティの友達機能を使うにはログインしてください。', '登录后即可使用社区好友功能。', '커뮤니티 친구 기능을 사용하려면 로그인하세요.', 'Connectez-vous pour utiliser les fonctions d’amis de la communauté.', 'Melde dich an, um die Freundesfunktionen der Community zu nutzen.', 'Inicia sesión para usar las funciones de amigos de la comunidad.', 'Войдите, чтобы пользоваться функциями друзей сообщества.', 'Entre para usar os recursos de amigos da comunidade.'],
  login_btn: ['Đăng nhập', 'Sign in', 'ログイン', '登录', '로그인', 'Connexion', 'Anmelden', 'Iniciar sesión', 'Войти', 'Entrar'],
  err_missing_title: ['Chưa thiết lập cơ sở dữ liệu cộng đồng', 'Community database is not set up', 'コミュニティのデータベースが未設定です', '尚未设置社区数据库', '커뮤니티 데이터베이스가 설정되지 않았습니다', 'La base de données de la communauté n’est pas configurée', 'Die Community-Datenbank ist nicht eingerichtet', 'La base de datos de la comunidad no está configurada', 'База данных сообщества не настроена', 'O banco de dados da comunidade não está configurado'],
  err_missing_body: ['Chạy file community_setup.sql trong Supabase → SQL Editor một lần, rồi bấm Thử lại.', 'Run community_setup.sql once in Supabase → SQL Editor, then press Retry.', 'Supabase の SQL Editor で community_setup.sql を一度実行し、「再試行」を押してください。', '在 Supabase → SQL Editor 中运行一次 community_setup.sql，然后点击“重试”。', 'Supabase → SQL Editor에서 community_setup.sql을 한 번 실행한 뒤 “다시 시도”를 누르세요.', 'Exécutez une fois community_setup.sql dans Supabase → SQL Editor, puis cliquez sur Réessayer.', 'Führe community_setup.sql einmal in Supabase → SQL Editor aus und klicke dann auf Erneut versuchen.', 'Ejecuta community_setup.sql una vez en Supabase → SQL Editor y pulsa Reintentar.', 'Один раз выполните community_setup.sql в Supabase → SQL Editor, затем нажмите «Повторить».', 'Execute community_setup.sql uma vez no Supabase → SQL Editor e clique em Tentar novamente.'],
  err_failed: ['Không tải được dữ liệu cộng đồng.', 'Couldn’t load community data.', 'コミュニティのデータを読み込めませんでした。', '无法加载社区数据。', '커뮤니티 데이터를 불러오지 못했습니다.', 'Impossible de charger les données de la communauté.', 'Community-Daten konnten nicht geladen werden.', 'No se pudieron cargar los datos de la comunidad.', 'Не удалось загрузить данные сообщества.', 'Não foi possível carregar os dados da comunidade.'],
  retry: ['Thử lại', 'Retry', '再試行', '重试', '다시 시도', 'Réessayer', 'Erneut versuchen', 'Reintentar', 'Повторить', 'Tentar novamente'],
  loading: ['Đang tải…', 'Loading…', '読み込み中…', '加载中…', '불러오는 중…', 'Chargement…', 'Wird geladen…', 'Cargando…', 'Загрузка…', 'Carregando…'],
  n_sent: ['Đã gửi lời mời kết bạn', 'Friend request sent', 'フレンドリクエストを送信しました', '已发送好友请求', '친구 요청을 보냈습니다', 'Demande d’ami envoyée', 'Freundschaftsanfrage gesendet', 'Solicitud de amistad enviada', 'Заявка в друзья отправлена', 'Pedido de amizade enviado'],
  n_accepted: ['Các bạn đã trở thành bạn bè', 'You are now friends', '友達になりました', '你们已成为好友', '이제 친구입니다', 'Vous êtes maintenant amis', 'Ihr seid jetzt befreundet', 'Ahora son amigos', 'Теперь вы друзья', 'Vocês agora são amigos'],
  n_removed: ['Đã xóa', 'Removed', '削除しました', '已移除', '삭제되었습니다', 'Supprimé', 'Entfernt', 'Eliminado', 'Удалено', 'Removido'],
  n_unfriended: ['Đã hủy kết bạn', 'Unfriended', '友達を解除しました', '已解除好友', '친구를 끊었습니다', 'Ami retiré', 'Freundschaft beendet', 'Amistad eliminada', 'Удалено из друзей', 'Amizade desfeita'],
  n_list_created: ['Đã tạo danh sách', 'List created', 'リストを作成しました', '列表已创建', '목록을 만들었습니다', 'Liste créée', 'Liste erstellt', 'Lista creada', 'Список создан', 'Lista criada'],
  n_list_deleted: ['Đã xóa danh sách', 'List deleted', 'リストを削除しました', '列表已删除', '목록을 삭제했습니다', 'Liste supprimée', 'Liste gelöscht', 'Lista eliminada', 'Список удалён', 'Lista excluída'],
  n_list_updated: ['Đã cập nhật danh sách', 'List updated', 'リストを更新しました', '列表已更新', '목록을 업데이트했습니다', 'Liste mise à jour', 'Liste aktualisiert', 'Lista actualizada', 'Список обновлён', 'Lista atualizada'],
  uid_label: ['Mã định danh (ID)', 'Account ID', 'アカウントID', '账户 ID', '계정 ID', 'Identifiant du compte', 'Konto-ID', 'ID de cuenta', 'ID аккаунта', 'ID da conta'],
  uid_hint: ['Dãy 8 số riêng của bạn. Người khác nhập mã này vào ô tìm kiếm để tìm đúng bạn.', 'Your unique 8-digit number. Others can enter it in search to find you.', 'あなた専用の8桁の番号です。検索欄に入力すると、あなたを見つけられます。', '您专属的 8 位数字。他人在搜索框输入即可找到您。', '나만의 8자리 번호입니다. 검색창에 입력하면 나를 찾을 수 있어요.', 'Votre numéro unique à 8 chiffres. Les autres peuvent le saisir dans la recherche pour vous trouver.', 'Deine eigene 8-stellige Nummer. Andere können sie in die Suche eingeben, um dich zu finden.', 'Tu número único de 8 dígitos. Otros pueden escribirlo en la búsqueda para encontrarte.', 'Ваш уникальный 8-значный номер. Введите его в поиске, чтобы найти вас.', 'Seu número único de 8 dígitos. Outros podem digitá-lo na busca para encontrar você.'],
  uid_copy: ['Sao chép', 'Copy', 'コピー', '复制', '복사', 'Copier', 'Kopieren', 'Copiar', 'Копировать', 'Copiar'],
  uid_copied: ['Đã sao chép', 'Copied', 'コピーしました', '已复制', '복사됨', 'Copié', 'Kopiert', 'Copiado', 'Скопировано', 'Copiado'],
  n_saved: ['Đã lưu hồ sơ', 'Profile saved', 'プロフィールを保存しました', '资料已保存', '프로필을 저장했습니다', 'Profil enregistré', 'Profil gespeichert', 'Perfil guardado', 'Профиль сохранён', 'Perfil salvo'],
};

export const COMMUNITY_TEXT = {};
ORDER.forEach((code) => { COMMUNITY_TEXT[code] = {}; });
Object.entries(E).forEach(([key, arr]) => {
  ORDER.forEach((code, i) => { COMMUNITY_TEXT[code][key] = arr[i]; });
});
