import { createContext, useContext, useState } from 'react';

export const LANGUAGES = [
  { code: 'vi', label: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'ja', label: '日本語 (Japanese)', flag: '🇯🇵' },
  { code: 'zh', label: '中文 (Chinese)', flag: '🇨🇳' },
  { code: 'ko', label: '한국어 (Korean)', flag: '🇰🇷' },
  { code: 'fr', label: 'Français (French)', flag: '🇫🇷' },
  { code: 'de', label: 'Deutsch (German)', flag: '🇩🇪' },
  { code: 'es', label: 'Español (Spanish)', flag: '🇪🇸' },
  { code: 'ru', label: 'Русский (Russian)', flag: '🇷🇺' },
  { code: 'pt', label: 'Português (Portuguese)', flag: '🇧🇷' },
];

export const TRANSLATIONS = {
  vi: {
    community: 'Cộng đồng', about: 'Giới thiệu', support: 'Hỗ trợ', language: 'Ngôn ngữ', register: 'Đăng ký', signin: 'Đăng nhập', signout: 'Đăng xuất',
    welcome_sub: '▲ HÀNH TRÌNH ĐẾN NHỮNG VÙNG ĐẤT MỚI, KHÁM PHÁ VƯỜN QUỐC GIA NOTO',
    welcome_title: 'WELCOME',
    welcome_desc: 'Rời xa sự náo nhiệt của những đô thị sầm uất tại Nhật Bản là ngôi làng cổ Noto thanh bình, ẩn chứa những điều bất ngờ đầy cuốn hút.',
    start_journey: 'Bắt đầu hành trình ▸',
    experience_3d: 'TRẢI NGHIỆM 3D',
    tranquility: 'Thanh Bình',
    tranquility_desc: 'Tách biệt khỏi nhịp sống hối hả, đắm mình vào những dòng thác lung linh và hồ nước huyền bí nơi lưu giữ kho tàng mã nguồn mở huyền thoại.',
    learn_more: '— Tìm hiểu thêm',
    profile_details: 'Chi tiết hồ sơ', saved_repos: 'Kho lưu trữ đã lưu', history: 'Lịch sử hoạt động',
    all_repos: 'Tất cả kho lưu trữ', search_placeholder: 'Tìm kiếm kho lưu trữ, framework...',
    quick_view: 'Xem nhanh 👁',
    about_badge: 'VỀ DỰ ÁN NÀY',
    about_title: 'Cổng Khám Phá Mã Nguồn Mở Hiệu Năng Cao',
    about_sub: 'Được xây dựng nhằm tối ưu hóa việc tìm kiếm công nghệ, GitXplore là thư viện trực quan hướng dẫn lập trình viên đến với mã nguồn xuất sắc.',
    stat_repos: 'Kho lưu trữ tuyển chọn', stat_domains: 'Lĩnh vực công nghệ', stat_foss: 'Mã nguồn mở miễn phí', stat_updates: 'Cập nhật xu hướng',
    cta_title: 'Bạn có dự án mã nguồn mở muốn giới thiệu?',
    cta_sub: 'Đóng góp kho lưu trữ của bạn hoặc chia sẻ các phát hiện sáng tạo để phát triển cộng đồng.',
    cta_btn: 'Đóng góp trên GitHub ↗',
    acc_title: 'Trung tâm tài khoản',
    acc_sub: 'Quản lý trải nghiệm kết nối và cài đặt hồ sơ lập trình viên trên các nền tảng GitXplore.',
    acc_profiles_title: 'Hồ sơ và thông tin cá nhân',
    acc_settings: 'Cài đặt tài khoản',
    acc_sec: 'Mật khẩu và bảo mật', acc_conn: 'Trải nghiệm kết nối', acc_perm: 'Thông tin và quyền hạn', acc_act: 'Theo dõi & Hoạt động dự án', acc_bill: 'Thanh toán & Giao dịch', acc_sub_menu: 'Tài trợ & Đăng ký', acc_manage: 'Quản lý tài khoản',
    acc_return: '← Quay lại GitXplore'
  },
  en: {
    community: 'Community', about: 'About', support: 'Support', language: 'Language', register: 'Register', signin: 'Sign in', signout: 'Sign out',
    welcome_sub: '▲ JOURNEY TO NEW FRONTIERS, JOURNEY TO NOTO NATURE PARK',
    welcome_title: 'WELCOME',
    welcome_desc: "Away from the manic energy of Japan's famous metropolises lies the ancient hamlet of Noto. Surprising and captivating in equal measure.",
    start_journey: 'Start the journey ▸',
    experience_3d: '3D EXPERIENCE',
    tranquility: 'Tranquility',
    tranquility_desc: "Away from the manic energy of Japan's famous metropolises, soak into the ethereal waterfalls and mystic lakes harboring a vast realm of legendary open-source artifacts.",
    learn_more: '— Learn more',
    profile_details: 'Profile details', saved_repos: 'Saved Repositories', history: 'History',
    all_repos: 'All Repositories', search_placeholder: 'Search repositories, frameworks...',
    quick_view: 'Quick View 👁',
    about_badge: 'ABOUT THE INITIATIVE',
    about_title: 'A Curated Portal for High-Performance Open-Source Artifacts',
    about_sub: 'Born to streamline technical discovery, GitXplore serves as an immersive visual library guiding developers directly to exceptional code.',
    stat_repos: 'Selected Repositories', stat_domains: 'Tech Domains', stat_foss: 'Free & Open Source', stat_updates: 'Trending Updates',
    cta_title: 'Have an open-source project to feature?',
    cta_sub: 'Contribute your repository or share innovative discoveries to strengthen the global open-source landscape.',
    cta_btn: 'Contribute on GitHub ↗',
    acc_title: 'Accounts Center',
    acc_sub: 'Manage your connected experiences and developer profile settings across GitXplore technologies.',
    acc_profiles_title: 'Profiles and personal details',
    acc_settings: 'Account settings',
    acc_sec: 'Password and security', acc_conn: 'Connected experiences', acc_perm: 'Your information and permissions', acc_act: 'Project activity & tracking', acc_bill: 'Billing & Payments', acc_sub_menu: 'Sponsorships & Subscriptions', acc_manage: 'Manage accounts',
    acc_return: '← Return to GitXplore'
  },
  ja: {
    community: 'コミュニティ', about: '概要', support: 'サポート', language: '言語', register: '新規登録', signin: 'ログイン', signout: 'ログアウト',
    welcome_sub: '▲ 新たなフロンティアへ、能登自然公園への旅',
    welcome_title: 'ようこそ',
    welcome_desc: '大都市の喧騒から離れた能登の古き集落。驚きと魅力に満ちた静寂の世界。',
    start_journey: '旅を始める ▸',
    experience_3d: '3D 体験',
    tranquility: '静寂',
    tranquility_desc: '神秘的な滝と静かな湖に囲まれた、オープンソースの宝庫を探索しましょう。',
    learn_more: '— 詳細を見る',
    profile_details: 'プロフィール詳細', saved_repos: '保存したリポジトリ', history: 'アクティビティ履歴',
    all_repos: 'すべてのリポジトリ', search_placeholder: 'リポジトリ、フレームワークを検索...',
    quick_view: 'クイックビュー 👁',
    about_badge: 'プロジェクトについて',
    about_title: '高性能オープンソースの厳選ポータル',
    about_sub: 'GitXploreは、開発者が優れたコードに直接アクセスできるように導くビジュアルライブラリです。',
    stat_repos: '厳選されたリポジトリ', stat_domains: '技術分野', stat_foss: '完全オープンソース', stat_updates: 'トレンド更新',
    cta_title: '紹介したいプロジェクトはありますか？',
    cta_sub: 'リポジトリを提供して、世界のオープンソースエコシステムを強化しましょう。',
    cta_btn: 'GitHubで貢献 ↗',
    acc_title: 'アカウントセンター',
    acc_sub: 'GitXplore全体で連携設定と開発者プロファイルを管理します。',
    acc_profiles_title: 'プロフィールと個人情報',
    acc_settings: 'アカウント設定',
    acc_sec: 'パスワードとセキュリティ', acc_conn: '連携エクスペリエンス', acc_perm: '情報とアクセス許可', acc_act: 'プロジェクトのアクティビティ', acc_bill: '請求と支払い', acc_sub_menu: 'スポンサーシップとサブスクリプション', acc_manage: 'アカウント管理',
    acc_return: '← GitXploreに戻る'
  },
  zh: {
    community: '社区', about: '关于我们', support: '技术支持', language: '语言', register: '注册', signin: '登录', signout: '退出登录',
    welcome_sub: '▲ 开启全新旅程，探索能登自然公园',
    welcome_title: '欢迎',
    welcome_desc: '远离大都市的喧嚣繁华，步入能登古老村落，探索充满魅力与惊喜的宝藏。',
    start_journey: '启程探索 ▸',
    experience_3d: '3D 体验',
    tranquility: '宁静',
    tranquility_desc: '沉浸于清澈瀑布与神秘湖泊之间，探索浩瀚的开源传奇代码库。',
    learn_more: '— 了解更多',
    profile_details: '个人资料详情', saved_repos: '已收藏的仓库', history: '活动历史',
    all_repos: '所有开源仓库', search_placeholder: '搜索仓库、框架...',
    quick_view: '快速预览 👁',
    about_badge: '关于此项目',
    about_title: '高性能开源宝藏精选平台',
    about_sub: 'GitXplore 作为沉浸式代码库导航，引领开发者轻松探索全球顶级代码。',
    stat_repos: '精选仓库', stat_domains: '技术领域', stat_foss: '完全免费开源', stat_updates: '每日趋势更新',
    cta_title: '想要推荐您的开源项目？',
    cta_sub: '贡献您的开源仓库，共同繁荣全球开源生态。',
    cta_btn: '在 GitHub 上贡献 ↗',
    acc_title: '账户中心',
    acc_sub: '管理您在 GitXplore 生态下的关联体验及开发者配置。',
    acc_profiles_title: '个人主页与详情',
    acc_settings: '账户设置',
    acc_sec: '密码与安全', acc_conn: '关联体验', acc_perm: '信息与权限', acc_act: '项目活动跟踪', acc_bill: '账单与支付', acc_sub_menu: '赞助与订阅', acc_manage: '管理账户',
    acc_return: '← 返回 GitXplore'
  },
  ko: {
    community: '커뮤니티', about: '소개', support: '고객지원', language: '언어', register: '회원가입', signin: '로그인', signout: '로그아웃',
    welcome_sub: '▲ 새로운 경계를 향한 여정, 노토 자연공원으로',
    welcome_title: '환영합니다',
    welcome_desc: '대도시의 복잡함을 벗어나 고요한 노토 마을에서 만나는 매혹적인 여정.',
    start_journey: '여정 시작 ▸',
    experience_3d: '3D 체험',
    tranquility: '평온',
    tranquility_desc: '신비로운 폭포와 호수 속에 펼쳐진 오픈소스 유물의 세계를 경험하세요.',
    learn_more: '— 더 알아보기',
    profile_details: '프로필 상세', saved_repos: '저장된 저장소', history: '활동 기록',
    all_repos: '모든 저장소', search_placeholder: '저장소 및 프레임워크 검색...',
    quick_view: '빠른 보기 👁',
    about_badge: '프로젝트 정보',
    about_title: '고성능 오픈소스 큐레이션 포털',
    about_sub: 'GitXplore는 개발자가 탁월한 코드에 즉시 접근할 수 있도록 돕는 비주얼 라이브러리입니다.',
    stat_repos: '선정된 저장소', stat_domains: '기술 분야', stat_foss: '무료 오픈소스', stat_updates: '트렌드 업데이트',
    cta_title: '소개하고 싶은 프로젝트가 있으신가요?',
    cta_sub: '오픈소스 저장소를 기여하고 커뮤니티의 발전에 동참하세요.',
    cta_btn: 'GitHub에서 기여 ↗',
    acc_title: '계정 센터',
    acc_sub: 'GitXplore 서비스 전반의 연결 환경 및 개발자 설정을 관리합니다.',
    acc_profiles_title: '프로필 및 개인 정보',
    acc_settings: '계정 설정',
    acc_sec: '비밀번호 및 보안', acc_conn: '연결된 환경', acc_perm: '내 정보 및 권한', acc_act: '프로젝트 활동 및 추적', acc_bill: '결제 및 청구', acc_sub_menu: '후원 및 구독', acc_manage: '계정 관리',
    acc_return: '← GitXplore로 돌아가기'
  },
  fr: {
    community: 'Communauté', about: 'À propos', support: 'Assistance', language: 'Langue', register: "S'inscrire", signin: 'Connexion', signout: 'Déconnexion',
    welcome_sub: '▲ VOYAGE VERS DE NOUVELLES FRONTIÈRES, PARC NATUREL DE NOTO',
    welcome_title: 'BIENVENUE',
    welcome_desc: 'Loin du tumulte des métropoles japonaises, découvrez le paisible village de Noto.',
    start_journey: 'Commencer le voyage ▸',
    experience_3d: 'EXPÉRIENCE 3D',
    tranquility: 'Tranquillité',
    tranquility_desc: 'Plongez au cœur des cascades éthérées et découvrez un univers open-source légendaire.',
    learn_more: '— En savoir plus',
    profile_details: 'Détails du profil', saved_repos: 'Dépôts enregistrés', history: 'Historique',
    all_repos: 'Tous les dépôts', search_placeholder: 'Rechercher des dépôts, frameworks...',
    quick_view: 'Aperçu 👁',
    about_badge: "À PROPOS DE L'INITIATIVE",
    about_title: 'Portail Sélectif pour Projets Open-Source',
    about_sub: 'GitXplore sert de bibliothèque visuelle guidant directement les développeurs vers un code exceptionnel.',
    stat_repos: 'Dépôts sélectionnés', stat_domains: 'Domaines techniques', stat_foss: 'Open-Source Libre', stat_updates: 'Tendances du jour',
    cta_title: 'Vous avez un projet à mettre en avant ?',
    cta_sub: 'Contribuez avec votre dépôt pour renforcer la communauté.',
    cta_btn: 'Contribuer sur GitHub ↗',
    acc_title: 'Espace Comptes',
    acc_sub: 'Gérez vos expériences connectées et paramètres de profil.',
    acc_profiles_title: 'Profils et données personnelles',
    acc_settings: 'Paramètres du compte',
    acc_sec: 'Mot de passe et sécurité', acc_conn: 'Expériences connectées', acc_perm: 'Vos informations et autorisations', acc_act: 'Activité du projet', acc_bill: 'Facturation et paiements', acc_sub_menu: 'Parrainages et abonnements', acc_manage: 'Gérer les comptes',
    acc_return: '← Retour à GitXplore'
  },
  de: {
    community: 'Community', about: 'Über uns', support: 'Support', language: 'Sprache', register: 'Registrieren', signin: 'Anmelden', signout: 'Abmelden',
    welcome_sub: '▲ REISE ZU NEUEN HORIZONTEN, NOTO-NATURPARK',
    welcome_title: 'WILLKOMMEN',
    welcome_desc: 'Fernab der Hektik japanischer Metropolen liegt das historische Dorf Noto.',
    start_journey: 'Reise beginnen ▸',
    experience_3d: '3D-ERLEBNIS',
    tranquility: 'Ruhe',
    tranquility_desc: 'Tauchen Sie ein in geheimnisvolle Wasserfälle und legendäre Open-Source-Schätze.',
    learn_more: '— Mehr erfahren',
    profile_details: 'Profildetails', saved_repos: 'Gespeicherte Repositories', history: 'Aktivitätsverlauf',
    all_repos: 'Alle Repositories', search_placeholder: 'Repositories, Frameworks suchen...',
    quick_view: 'Schnellansicht 👁',
    about_badge: 'ÜBER DIE INITIATIVE',
    about_title: 'Kuratierte Plattform für Open-Source-Artefakte',
    about_sub: 'GitXplore führt Entwickler direkt zu außergewöhnlichem Quellcode.',
    stat_repos: 'Ausgewählte Repos', stat_domains: 'Fachbereiche', stat_foss: 'Kostenlos & Open-Source', stat_updates: 'Trend-Updates',
    cta_title: 'Möchten Sie ein Projekt vorstellen?',
    cta_sub: 'Bringen Sie Ihr Repository ein und stärken Sie die Community.',
    cta_btn: 'Auf GitHub beitragen ↗',
    acc_title: 'Kontenübersicht',
    acc_sub: 'Verwalten Sie Ihre Einstellungen und Profile auf GitXplore.',
    acc_profiles_title: 'Profile und persönliche Daten',
    acc_settings: 'Kontoeinstellungen',
    acc_sec: 'Passwort & Sicherheit', acc_conn: 'Verbundene Erlebnisse', acc_perm: 'Ihre Informationen & Berechtigungen', acc_act: 'Projektaktivitäten', acc_bill: 'Abrechnung & Zahlungen', acc_sub_menu: 'Sponsoring & Abonnements', acc_manage: 'Konten verwalten',
    acc_return: '← Zurück zu GitXplore'
  },
  es: {
    community: 'Comunidad', about: 'Acerca de', support: 'Soporte', language: 'Idioma', register: 'Registrarse', signin: 'Iniciar sesión', signout: 'Cerrar sesión',
    welcome_sub: '▲ VIAJE HACIA NUEVAS FRONTERAS, PARQUE NATURAL DE NOTO',
    welcome_title: 'BIENVENIDO',
    welcome_desc: 'Lejos del bullicio de las metrópolis japonesas, descubra la tranquilidad de Noto.',
    start_journey: 'Comenzar viaje ▸',
    experience_3d: 'EXPERIENCIA 3D',
    tranquility: 'Tranquilidad',
    tranquility_desc: 'Sumérjase en cascadas místicas que albergan un vasto reino de código abierto.',
    learn_more: '— Más información',
    profile_details: 'Detalles del perfil', saved_repos: 'Repositorios guardados', history: 'Historial',
    all_repos: 'Todos los repositorios', search_placeholder: 'Buscar repositorios, frameworks...',
    quick_view: 'Vista previa 👁',
    about_badge: 'ACERCA DE LA INICIATIVA',
    about_title: 'Portal Curado para Artefactos de Código Abierto',
    about_sub: 'GitXplore guía a los desarrolladores directamente al código excepcional.',
    stat_repos: 'Repositorios selectos', stat_domains: 'Áreas técnicas', stat_foss: 'Código Abierto Libre', stat_updates: 'Tendencias al día',
    cta_title: '¿Tienes un proyecto para destacar?',
    cta_sub: 'Contribuye con tu repositorio para enriquecer el ecosistema global.',
    cta_btn: 'Contribuir en GitHub ↗',
    acc_title: 'Centro de Cuentas',
    acc_sub: 'Administra tus experiencias conectadas y perfiles.',
    acc_profiles_title: 'Perfiles y datos personales',
    acc_settings: 'Configuración de la cuenta',
    acc_sec: 'Contraseña y seguridad', acc_conn: 'Experiencias conectadas', acc_perm: 'Tu información y permisos', acc_act: 'Actividad del proyecto', acc_bill: 'Facturación y pagos', acc_sub_menu: 'Patrocinios y suscripciones', acc_manage: 'Administrar cuentas',
    acc_return: '← Volver a GitXplore'
  },
  ru: {
    community: 'Сообщество', about: 'О нас', support: 'Поддержка', language: 'Язык', register: 'Регистрация', signin: 'Вход', signout: 'Выход',
    welcome_sub: '▲ ПУТЕШЕСТВИЕ К НОВЫМ ГОРИЗОНТАМ, ПРИРОДНЫЙ ПАРК НОТО',
    welcome_title: 'ДОБРО ПОЖАЛОВАТЬ',
    welcome_desc: 'Вдали от суеты японских мегаполисов лежит древняя деревня Ното.',
    start_journey: 'Начать путешествие ▸',
    experience_3d: '3D-ОПЫТ',
    tranquility: 'Спокойствие',
    tranquility_desc: 'Погрузитесь в мистическую атмосферу водопадов и легендарных проектов с открытым кодом.',
    learn_more: '— Узнать больше',
    profile_details: 'Данные профиля', saved_repos: 'Сохраненные репозитории', history: 'История активности',
    all_repos: 'Все репозитории', search_placeholder: 'Поиск репозиториев, фреймворков...',
    quick_view: 'Просмотр 👁',
    about_badge: 'ОБ ИНИЦИАТИВЕ',
    about_title: 'Кураторский портал решений с открытым кодом',
    about_sub: 'GitXplore ведет разработчиков напрямую к передовому коду.',
    stat_repos: 'Избранные проекты', stat_domains: 'Технологические сферы', stat_foss: 'Бесплатно и Open-Source', stat_updates: 'Актуальные тренды',
    cta_title: 'Хотите добавить свой проект?',
    cta_sub: 'Поделитесь своим репозиторием и внесите вклад в сообщество.',
    cta_btn: 'Внести вклад на GitHub ↗',
    acc_title: 'Центр аккаунтов',
    acc_sub: 'Управляйте профилями и связанными сервисами.',
    acc_profiles_title: 'Профили и личные данные',
    acc_settings: 'Настройки аккаунта',
    acc_sec: 'Пароль и безопасность', acc_conn: 'Связанные сервисы', acc_perm: 'Информация и разрешения', acc_act: 'Активность проектов', acc_bill: 'Оплата и счета', acc_sub_menu: 'Спонсорство и подписки', acc_manage: 'Управление аккаунтами',
    acc_return: '← Вернуться в GitXplore'
  },
  pt: {
    community: 'Comunidade', about: 'Sobre', support: 'Suporte', language: 'Idioma', register: 'Cadastre-se', signin: 'Entrar', signout: 'Sair',
    welcome_sub: '▲ UMA JORNADA PARA NOVAS FRONTEIRAS, PARQUE NATURAL DE NOTO',
    welcome_title: 'BEM-VINDO',
    welcome_desc: 'Longe da energia agitada das metrópoles japonesas, repousa o vilarejo de Noto.',
    start_journey: 'Iniciar jornada ▸',
    experience_3d: 'EXPERIÊNCIA 3D',
    tranquilidade: 'Tranquilidade',
    tranquility_desc: 'Explore cachoeiras etéreas e lagos místicos repletos de artefatos open-source.',
    learn_more: '— Saiba mais',
    profile_details: 'Detalhes do perfil', saved_repos: 'Repositórios salvos', history: 'Histórico',
    all_repos: 'Todos os repositórios', search_placeholder: 'Buscar repositórios, frameworks...',
    quick_view: 'Ver detalhes 👁',
    about_badge: 'SOBRE A INICIATIVA',
    about_title: 'Portal Curado para Projetos de Código Aberto',
    about_sub: 'GitXplore guia desenvolvedores diretamente para códigos excepcionais.',
    stat_repos: 'Repositórios selecionados', stat_domains: 'Áreas de tecnologia', stat_foss: 'Livre e Open-Source', stat_updates: 'Tendências atuais',
    cta_title: 'Tem um projeto para destacar?',
    cta_sub: 'Contribua com seu repositório para fortalecer a comunidade.',
    cta_btn: 'Contribuir no GitHub ↗',
    acc_title: 'Central de Contas',
    acc_sub: 'Gerencie suas preferências e contas conectadas.',
    acc_profiles_title: 'Perfis e dados pessoais',
    acc_settings: 'Configurações da conta',
    acc_sec: 'Senha e segurança', acc_conn: 'Experiências conectadas', acc_perm: 'Suas informações e permissões', acc_act: 'Atividade do projeto', acc_bill: 'Faturamento e pagamentos', acc_sub_menu: 'Patrocínios e assinaturas', acc_manage: 'Gerenciar contas',
    acc_return: '← Voltar para GitXplore'
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('gxp_lang') || 'en');

  const changeLanguage = (code) => {
    setLang(code);
    localStorage.setItem('gxp_lang', code);
  };

  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en']?.[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}