/**
 * Chuỗi giao diện bổ sung cho 10 ngôn ngữ (thanh điều hướng, thanh tiện ích, Accounts Center).
 * LanguageContext tra cứu file này sau TRANSLATIONS, nên không phải sửa bảng cũ.
 */
export const UI_STRINGS = {
  vi: {
    ui_home: 'Trang chủ', ui_shortcuts: 'Lối tắt', ui_notifications: 'Thông báo', ui_account: 'Tài khoản',
    ui_main_nav: 'Điều hướng chính', ui_dock_rail: 'Thanh tiện ích', ui_dock_notes: 'Ghi chú nhanh',
    ui_dock_news_desc: 'Tin mới về mã nguồn mở', ui_dock_comm_desc: 'Thảo luận, hỏi đáp, chia sẻ',
    ui_dock_acc_in: 'Repo đã lưu, hồ sơ, lịch sử', ui_dock_acc_out: 'Đăng nhập để sử dụng',
    ui_dock_support_desc: 'Câu hỏi thường gặp, gửi yêu cầu',
    ui_dock_saved_login: 'Đăng nhập để xem các repo bạn đã lưu.',
    ui_dock_saved_empty: 'Bạn chưa lưu repo nào. Mở một dự án và bấm “Lưu Repo”.',
    ui_dock_notes_ph: 'Ghi lại ý tưởng, tên repo muốn xem sau…', ui_dock_notes_hint: 'Tự động lưu trên trình duyệt này.',
    ui_close: 'Đóng', ui_acc_language: 'Ngôn ngữ',
    ui_acc_language_sub: 'Chọn ngôn ngữ hiển thị của GitXplore. Lựa chọn được lưu trên trình duyệt này.',
    ui_current: 'Đang dùng', ui_active: 'Đang đăng nhập:', ui_quick_vault: 'Kho nhanh',
  },
  en: {
    ui_home: 'Home', ui_shortcuts: 'Shortcuts', ui_notifications: 'Notifications', ui_account: 'Account',
    ui_main_nav: 'Main navigation', ui_dock_rail: 'Quick tools', ui_dock_notes: 'Quick notes',
    ui_dock_news_desc: 'Latest open-source news', ui_dock_comm_desc: 'Discuss, ask, share',
    ui_dock_acc_in: 'Saved repos, profile, history', ui_dock_acc_out: 'Sign in to use',
    ui_dock_support_desc: 'FAQ and submit a request',
    ui_dock_saved_login: 'Sign in to see the repos you saved.',
    ui_dock_saved_empty: 'You have not saved any repo yet. Open a project and press “Save Repo”.',
    ui_dock_notes_ph: 'Jot down ideas or repo names to check later…', ui_dock_notes_hint: 'Saved automatically in this browser.',
    ui_close: 'Close', ui_acc_language: 'Language',
    ui_acc_language_sub: 'Choose the display language for GitXplore. Your choice is saved in this browser.',
    ui_current: 'Current', ui_active: 'Signed in as:', ui_quick_vault: 'Quick Vault',
  },
  ja: {
    ui_home: 'ホーム', ui_shortcuts: 'ショートカット', ui_notifications: '通知', ui_account: 'アカウント',
    ui_main_nav: 'メインナビゲーション', ui_dock_rail: 'クイックツール', ui_dock_notes: 'クイックメモ',
    ui_dock_news_desc: 'オープンソースの最新ニュース', ui_dock_comm_desc: '議論・質問・共有',
    ui_dock_acc_in: '保存したリポジトリ、プロフィール、履歴', ui_dock_acc_out: 'ログインして利用',
    ui_dock_support_desc: 'よくある質問・リクエスト送信',
    ui_dock_saved_login: 'ログインすると保存したリポジトリを確認できます。',
    ui_dock_saved_empty: 'まだリポジトリを保存していません。プロジェクトを開いて「保存」を押してください。',
    ui_dock_notes_ph: 'アイデアや後で見るリポジトリ名をメモ…', ui_dock_notes_hint: 'このブラウザに自動保存されます。',
    ui_close: '閉じる', ui_acc_language: '言語',
    ui_acc_language_sub: 'GitXploreの表示言語を選択します。選択はこのブラウザに保存されます。',
    ui_current: '使用中', ui_active: 'ログイン中:', ui_quick_vault: 'クイックボルト',
  },
  zh: {
    ui_home: '首页', ui_shortcuts: '快捷方式', ui_notifications: '通知', ui_account: '账户',
    ui_main_nav: '主导航', ui_dock_rail: '快捷工具栏', ui_dock_notes: '快速笔记',
    ui_dock_news_desc: '开源最新资讯', ui_dock_comm_desc: '讨论、提问、分享',
    ui_dock_acc_in: '已收藏仓库、资料、历史', ui_dock_acc_out: '登录后使用',
    ui_dock_support_desc: '常见问题与提交请求',
    ui_dock_saved_login: '登录后查看你收藏的仓库。',
    ui_dock_saved_empty: '你还没有收藏任何仓库。打开一个项目并点击“收藏”。',
    ui_dock_notes_ph: '记录想法或稍后查看的仓库名…', ui_dock_notes_hint: '自动保存在此浏览器中。',
    ui_close: '关闭', ui_acc_language: '语言',
    ui_acc_language_sub: '选择 GitXplore 的显示语言。选择会保存在此浏览器中。',
    ui_current: '当前使用', ui_active: '当前登录：', ui_quick_vault: '快速收纳',
  },
  ko: {
    ui_home: '홈', ui_shortcuts: '바로가기', ui_notifications: '알림', ui_account: '계정',
    ui_main_nav: '메인 내비게이션', ui_dock_rail: '빠른 도구', ui_dock_notes: '빠른 메모',
    ui_dock_news_desc: '오픈소스 최신 소식', ui_dock_comm_desc: '토론, 질문, 공유',
    ui_dock_acc_in: '저장한 저장소, 프로필, 기록', ui_dock_acc_out: '로그인 후 사용',
    ui_dock_support_desc: '자주 묻는 질문 및 요청 보내기',
    ui_dock_saved_login: '로그인하면 저장한 저장소를 볼 수 있어요.',
    ui_dock_saved_empty: '아직 저장한 저장소가 없어요. 프로젝트를 열고 “저장”을 누르세요.',
    ui_dock_notes_ph: '아이디어나 나중에 볼 저장소 이름을 적어두세요…', ui_dock_notes_hint: '이 브라우저에 자동 저장됩니다.',
    ui_close: '닫기', ui_acc_language: '언어',
    ui_acc_language_sub: 'GitXplore 표시 언어를 선택하세요. 선택은 이 브라우저에 저장됩니다.',
    ui_current: '사용 중', ui_active: '로그인:', ui_quick_vault: '빠른 보관함',
  },
  fr: {
    ui_home: 'Accueil', ui_shortcuts: 'Raccourcis', ui_notifications: 'Notifications', ui_account: 'Compte',
    ui_main_nav: 'Navigation principale', ui_dock_rail: 'Outils rapides', ui_dock_notes: 'Notes rapides',
    ui_dock_news_desc: "Dernières actus open source", ui_dock_comm_desc: 'Discuter, demander, partager',
    ui_dock_acc_in: 'Dépôts enregistrés, profil, historique', ui_dock_acc_out: 'Connectez-vous pour utiliser',
    ui_dock_support_desc: 'FAQ et envoi de demande',
    ui_dock_saved_login: 'Connectez-vous pour voir vos dépôts enregistrés.',
    ui_dock_saved_empty: "Vous n'avez enregistré aucun dépôt. Ouvrez un projet et cliquez sur « Enregistrer ».",
    ui_dock_notes_ph: 'Notez des idées ou des dépôts à voir plus tard…', ui_dock_notes_hint: 'Enregistré automatiquement dans ce navigateur.',
    ui_close: 'Fermer', ui_acc_language: 'Langue',
    ui_acc_language_sub: "Choisissez la langue d'affichage de GitXplore. Votre choix est enregistré dans ce navigateur.",
    ui_current: 'Actuelle', ui_active: 'Connecté :', ui_quick_vault: 'Coffre rapide',
  },
  de: {
    ui_home: 'Startseite', ui_shortcuts: 'Verknüpfungen', ui_notifications: 'Benachrichtigungen', ui_account: 'Konto',
    ui_main_nav: 'Hauptnavigation', ui_dock_rail: 'Schnellwerkzeuge', ui_dock_notes: 'Schnellnotizen',
    ui_dock_news_desc: 'Neues aus Open Source', ui_dock_comm_desc: 'Diskutieren, fragen, teilen',
    ui_dock_acc_in: 'Gespeicherte Repos, Profil, Verlauf', ui_dock_acc_out: 'Zum Nutzen anmelden',
    ui_dock_support_desc: 'FAQ und Anfrage senden',
    ui_dock_saved_login: 'Melde dich an, um deine gespeicherten Repos zu sehen.',
    ui_dock_saved_empty: 'Du hast noch kein Repo gespeichert. Öffne ein Projekt und klicke auf „Speichern“.',
    ui_dock_notes_ph: 'Ideen oder Repo-Namen für später notieren…', ui_dock_notes_hint: 'Wird automatisch in diesem Browser gespeichert.',
    ui_close: 'Schließen', ui_acc_language: 'Sprache',
    ui_acc_language_sub: 'Wähle die Anzeigesprache von GitXplore. Deine Auswahl wird in diesem Browser gespeichert.',
    ui_current: 'Aktiv', ui_active: 'Angemeldet als:', ui_quick_vault: 'Schnellablage',
  },
  es: {
    ui_home: 'Inicio', ui_shortcuts: 'Accesos directos', ui_notifications: 'Notificaciones', ui_account: 'Cuenta',
    ui_main_nav: 'Navegación principal', ui_dock_rail: 'Herramientas rápidas', ui_dock_notes: 'Notas rápidas',
    ui_dock_news_desc: 'Últimas noticias de código abierto', ui_dock_comm_desc: 'Debatir, preguntar, compartir',
    ui_dock_acc_in: 'Repos guardados, perfil, historial', ui_dock_acc_out: 'Inicia sesión para usar',
    ui_dock_support_desc: 'Preguntas frecuentes y enviar solicitud',
    ui_dock_saved_login: 'Inicia sesión para ver los repos que guardaste.',
    ui_dock_saved_empty: 'Aún no guardaste ningún repo. Abre un proyecto y pulsa “Guardar”.',
    ui_dock_notes_ph: 'Anota ideas o nombres de repos para ver después…', ui_dock_notes_hint: 'Se guarda automáticamente en este navegador.',
    ui_close: 'Cerrar', ui_acc_language: 'Idioma',
    ui_acc_language_sub: 'Elige el idioma de GitXplore. Tu elección se guarda en este navegador.',
    ui_current: 'Actual', ui_active: 'Sesión de:', ui_quick_vault: 'Bóveda rápida',
  },
  ru: {
    ui_home: 'Главная', ui_shortcuts: 'Быстрые ссылки', ui_notifications: 'Уведомления', ui_account: 'Аккаунт',
    ui_main_nav: 'Главная навигация', ui_dock_rail: 'Быстрые инструменты', ui_dock_notes: 'Быстрые заметки',
    ui_dock_news_desc: 'Свежие новости open source', ui_dock_comm_desc: 'Обсуждать, спрашивать, делиться',
    ui_dock_acc_in: 'Сохранённые репозитории, профиль, история', ui_dock_acc_out: 'Войдите, чтобы использовать',
    ui_dock_support_desc: 'Частые вопросы и отправка запроса',
    ui_dock_saved_login: 'Войдите, чтобы увидеть сохранённые репозитории.',
    ui_dock_saved_empty: 'Вы пока ничего не сохранили. Откройте проект и нажмите «Сохранить».',
    ui_dock_notes_ph: 'Записывайте идеи и названия репозиториев на потом…', ui_dock_notes_hint: 'Сохраняется автоматически в этом браузере.',
    ui_close: 'Закрыть', ui_acc_language: 'Язык',
    ui_acc_language_sub: 'Выберите язык интерфейса GitXplore. Выбор сохраняется в этом браузере.',
    ui_current: 'Текущий', ui_active: 'Вы вошли как:', ui_quick_vault: 'Быстрое хранилище',
  },
  pt: {
    ui_home: 'Início', ui_shortcuts: 'Atalhos', ui_notifications: 'Notificações', ui_account: 'Conta',
    ui_main_nav: 'Navegação principal', ui_dock_rail: 'Ferramentas rápidas', ui_dock_notes: 'Notas rápidas',
    ui_dock_news_desc: 'Últimas notícias de código aberto', ui_dock_comm_desc: 'Debater, perguntar, compartilhar',
    ui_dock_acc_in: 'Repositórios salvos, perfil, histórico', ui_dock_acc_out: 'Entre para usar',
    ui_dock_support_desc: 'Perguntas frequentes e enviar pedido',
    ui_dock_saved_login: 'Entre para ver os repositórios que você salvou.',
    ui_dock_saved_empty: 'Você ainda não salvou nenhum repositório. Abra um projeto e clique em “Salvar”.',
    ui_dock_notes_ph: 'Anote ideias ou nomes de repositórios para ver depois…', ui_dock_notes_hint: 'Salvo automaticamente neste navegador.',
    ui_close: 'Fechar', ui_acc_language: 'Idioma',
    ui_acc_language_sub: 'Escolha o idioma do GitXplore. Sua escolha fica salva neste navegador.',
    ui_current: 'Atual', ui_active: 'Conectado como:', ui_quick_vault: 'Cofre rápido',
  },
};
